
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

[[constraint]]
  version = "v0.0.2"
  name = "github.com/previousnext/compose"

[[constraint]]
  revision = "500ce4a511436e00d4b60c72aed8ead1a5c4c822"
  name = "github.com/fsouza/go-dockerclient"

[[constraint]]
  branch = "master"
  name = "github.com/golang/protobuf"

[[constraint]]
  branch = "master"
  name = "github.com/gosexy/to"

[[constraint]]
  name = "github.com/nlopes/slack"
  version = "0.1.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/smallfish/simpleyaml"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.6.0"

[[constraint]]
  name = "gopkg.in/alecthomas/kingpin.v2"
  version = "2.2.5"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.9.2"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.9.2"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.9.2"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.9.2"

[[override]]
  name = "github.com/ugorji/go"
  revision = "8c0409fcbb70099c748d71f714529204975f6c3f"
